In [3]:
import pandas as pd
from pathlib import Path


BASE_DIR = Path.cwd()

if BASE_DIR.name == "notebooks":
    BASE_DIR = BASE_DIR.parent


RAW_DATA = BASE_DIR / "data" / "raw" / "consulta_cand_2026_BRASIL.csv"

PROCESSED_DATA = BASE_DIR / "data" / "processed"


print(RAW_DATA)
print(PROCESSED_DATA)

C:\Users\Fernando\eleicoes-brasil-analytics\data\raw\consulta_cand_2026_BRASIL.csv
C:\Users\Fernando\eleicoes-brasil-analytics\data\processed

In [4]:
df = pd.read_csv(
    RAW_DATA,
    sep=";",
    encoding="latin1"
)

df.shape

(20721, 50)

In [5]:
df_tratado = df.copy()

df_tratado.head()

,DT_GERACAO,HH_GERACAO,ANO_ELEICAO,CD_TIPO_ELEICAO,NM_TIPO_ELEICAO,NR_TURNO,CD_ELEICAO,DS_ELEICAO,DT_ELEICAO,TP_ABRANGENCIA,...,CD_GRAU_INSTRUCAO,DS_GRAU_INSTRUCAO,CD_ESTADO_CIVIL,DS_ESTADO_CIVIL,CD_COR_RACA,DS_COR_RACA,CD_OCUPACAO,DS_OCUPACAO,CD_SIT_TOT_TURNO,DS_SIT_TOT_TURNO
0,24/08/2026,16:31:10,2026,2,ELEIÇÃO ORDINÁRIA,1,6259,Eleições Gerais Estaduais 2026,04/10/2026,ESTADUAL,...,7,SUPERIOR INCOMPLETO,3,CASADO(A),3,PARDA,999,OUTROS,-1,#NULO
1,24/08/2026,16:31:10,2026,2,ELEIÇÃO ORDINÁRIA,1,6259,Eleições Gerais Estaduais 2026,04/10/2026,ESTADUAL,...,8,SUPERIOR COMPLETO,3,CASADO(A),1,BRANCA,602,PECUARISTA,-1,#NULO
2,24/08/2026,16:31:10,2026,2,ELEIÇÃO ORDINÁRIA,1,6259,Eleições Gerais Estaduais 2026,04/10/2026,ESTADUAL,...,8,SUPERIOR COMPLETO,1,SOLTEIRO(A),1,BRANCA,142,PROFESSOR DE ENSINO SUPERIOR,-1,#NULO
3,24/08/2026,16:31:10,2026,2,ELEIÇÃO ORDINÁRIA,1,6259,Eleições Gerais Estaduais 2026,04/10/2026,ESTADUAL,...,7,SUPERIOR INCOMPLETO,1,SOLTEIRO(A),3,PARDA,931,"ESTUDANTE, BOLSISTA, ESTAGIÁRIO E ASSEMELHADOS",-1,#NULO
4,24/08/2026,16:31:10,2026,2,ELEIÇÃO ORDINÁRIA,1,6259,Eleições Gerais Estaduais 2026,04/10/2026,ESTADUAL,...,8,SUPERIOR COMPLETO,3,CASADO(A),5,INDÍGENA,999,OUTROS,-1,#NULO

In [6]:
colunas_remover = [
    "NR_CPF_CANDIDATO",
    "NR_TITULO_ELEITORAL_CANDIDATO",
    "DS_EMAIL"
]


df_tratado = df_tratado.drop(
    columns=colunas_remover
)


df_tratado.shape

(20721, 47)

In [7]:
renomear = {
    "NM_CANDIDATO": "nome_candidato",
    "NM_URNA_CANDIDATO": "nome_urna",
    "DS_CARGO": "cargo",
    "SG_PARTIDO": "partido",
    "NM_PARTIDO": "nome_partido",
    "SG_UF": "estado",
    "NM_UE": "estado_nome",
    "DS_GENERO": "genero",
    "DS_GRAU_INSTRUCAO": "escolaridade",
    "DS_ESTADO_CIVIL": "estado_civil",
    "DS_COR_RACA": "cor_raca",
    "DS_OCUPACAO": "ocupacao",
    "DS_SIT_TOT_TURNO": "situacao_final"
}


df_tratado = df_tratado.rename(
    columns=renomear
)


df_tratado.head()

,DT_GERACAO,HH_GERACAO,ANO_ELEICAO,CD_TIPO_ELEICAO,NM_TIPO_ELEICAO,NR_TURNO,CD_ELEICAO,DS_ELEICAO,DT_ELEICAO,TP_ABRANGENCIA,...,CD_GRAU_INSTRUCAO,escolaridade,CD_ESTADO_CIVIL,estado_civil,CD_COR_RACA,cor_raca,CD_OCUPACAO,ocupacao,CD_SIT_TOT_TURNO,situacao_final
0,24/08/2026,16:31:10,2026,2,ELEIÇÃO ORDINÁRIA,1,6259,Eleições Gerais Estaduais 2026,04/10/2026,ESTADUAL,...,7,SUPERIOR INCOMPLETO,3,CASADO(A),3,PARDA,999,OUTROS,-1,#NULO
1,24/08/2026,16:31:10,2026,2,ELEIÇÃO ORDINÁRIA,1,6259,Eleições Gerais Estaduais 2026,04/10/2026,ESTADUAL,...,8,SUPERIOR COMPLETO,3,CASADO(A),1,BRANCA,602,PECUARISTA,-1,#NULO
2,24/08/2026,16:31:10,2026,2,ELEIÇÃO ORDINÁRIA,1,6259,Eleições Gerais Estaduais 2026,04/10/2026,ESTADUAL,...,8,SUPERIOR COMPLETO,1,SOLTEIRO(A),1,BRANCA,142,PROFESSOR DE ENSINO SUPERIOR,-1,#NULO
3,24/08/2026,16:31:10,2026,2,ELEIÇÃO ORDINÁRIA,1,6259,Eleições Gerais Estaduais 2026,04/10/2026,ESTADUAL,...,7,SUPERIOR INCOMPLETO,1,SOLTEIRO(A),3,PARDA,931,"ESTUDANTE, BOLSISTA, ESTAGIÁRIO E ASSEMELHADOS",-1,#NULO
4,24/08/2026,16:31:10,2026,2,ELEIÇÃO ORDINÁRIA,1,6259,Eleições Gerais Estaduais 2026,04/10/2026,ESTADUAL,...,8,SUPERIOR COMPLETO,3,CASADO(A),5,INDÍGENA,999,OUTROS,-1,#NULO

In [8]:
df_tratado.info()

<class 'pandas.DataFrame'>
RangeIndex: 20721 entries, 0 to 20720
Data columns (total 47 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   DT_GERACAO               20721 non-null  str
 1   HH_GERACAO               20721 non-null  str
 2   ANO_ELEICAO              20721 non-null  int64
 3   CD_TIPO_ELEICAO          20721 non-null  int64
 4   NM_TIPO_ELEICAO          20721 non-null  str
 5   NR_TURNO                 20721 non-null  int64
 6   CD_ELEICAO               20721 non-null  int64
 7   DS_ELEICAO               20721 non-null  str
 8   DT_ELEICAO               20721 non-null  str
 9   TP_ABRANGENCIA           20721 non-null  str
 10  estado                   20721 non-null  str
 11  SG_UE                    20721 non-null  str
 12  estado_nome              20721 non-null  str
 13  CD_CARGO                 20721 non-null  int64
 14  cargo                    20721 non-null  str
 15  SQ_CANDIDATO             20721 non-null  int64
 16  NR_CANDIDATO             20721 non-null  int64
 17  nome_candidato           20721 non-null  str
 18  nome_urna                20721 non-null  str
 19  NM_SOCIAL_CANDIDATO      20721 non-null  str
 20  CD_SITUACAO_CANDIDATURA  20721 non-null  int64
 21  DS_SITUACAO_CANDIDATURA  20721 non-null  str
 22  TP_AGREMIACAO            20721 non-null  str
 23  NR_PARTIDO               20721 non-null  int64
 24  partido                  20721 non-null  str
 25  nome_partido             20721 non-null  str
 26  NR_FEDERACAO             20721 non-null  int64
 27  NM_FEDERACAO             20721 non-null  str
 28  SG_FEDERACAO             20721 non-null  str
 29  DS_COMPOSICAO_FEDERACAO  20721 non-null  str
 30  SQ_COLIGACAO             20721 non-null  int64
 31  NM_COLIGACAO             20721 non-null  str
 32  DS_COMPOSICAO_COLIGACAO  20721 non-null  str
 33  SG_UF_NASCIMENTO         20721 non-null  str
 34  DT_NASCIMENTO            20721 non-null  str
 35  CD_GENERO                20721 non-null  int64
 36  genero                   20721 non-null  str
 37  CD_GRAU_INSTRUCAO        20721 non-null  int64
 38  escolaridade             20721 non-null  str
 39  CD_ESTADO_CIVIL          20721 non-null  int64
 40  estado_civil             20721 non-null  str
 41  CD_COR_RACA              20721 non-null  int64
 42  cor_raca                 20721 non-null  str
 43  CD_OCUPACAO              20721 non-null  int64
 44  ocupacao                 20721 non-null  str
 45  CD_SIT_TOT_TURNO         20721 non-null  int64
 46  situacao_final           20721 non-null  str
dtypes: int64(17), str(30)
memory usage: 14.2 MB

In [9]:
valores_invalidos = [
    "#NULO",
    "#NE"
]


df_tratado = df_tratado.replace(
    valores_invalidos,
    "Não informado"
)


df_tratado.head()

,DT_GERACAO,HH_GERACAO,ANO_ELEICAO,CD_TIPO_ELEICAO,NM_TIPO_ELEICAO,NR_TURNO,CD_ELEICAO,DS_ELEICAO,DT_ELEICAO,TP_ABRANGENCIA,...,CD_GRAU_INSTRUCAO,escolaridade,CD_ESTADO_CIVIL,estado_civil,CD_COR_RACA,cor_raca,CD_OCUPACAO,ocupacao,CD_SIT_TOT_TURNO,situacao_final
0,24/08/2026,16:31:10,2026,2,ELEIÇÃO ORDINÁRIA,1,6259,Eleições Gerais Estaduais 2026,04/10/2026,ESTADUAL,...,7,SUPERIOR INCOMPLETO,3,CASADO(A),3,PARDA,999,OUTROS,-1,Não informado
1,24/08/2026,16:31:10,2026,2,ELEIÇÃO ORDINÁRIA,1,6259,Eleições Gerais Estaduais 2026,04/10/2026,ESTADUAL,...,8,SUPERIOR COMPLETO,3,CASADO(A),1,BRANCA,602,PECUARISTA,-1,Não informado
2,24/08/2026,16:31:10,2026,2,ELEIÇÃO ORDINÁRIA,1,6259,Eleições Gerais Estaduais 2026,04/10/2026,ESTADUAL,...,8,SUPERIOR COMPLETO,1,SOLTEIRO(A),1,BRANCA,142,PROFESSOR DE ENSINO SUPERIOR,-1,Não informado
3,24/08/2026,16:31:10,2026,2,ELEIÇÃO ORDINÁRIA,1,6259,Eleições Gerais Estaduais 2026,04/10/2026,ESTADUAL,...,7,SUPERIOR INCOMPLETO,1,SOLTEIRO(A),3,PARDA,931,"ESTUDANTE, BOLSISTA, ESTAGIÁRIO E ASSEMELHADOS",-1,Não informado
4,24/08/2026,16:31:10,2026,2,ELEIÇÃO ORDINÁRIA,1,6259,Eleições Gerais Estaduais 2026,04/10/2026,ESTADUAL,...,8,SUPERIOR COMPLETO,3,CASADO(A),5,INDÍGENA,999,OUTROS,-1,Não informado

In [10]:
df_tratado["DT_NASCIMENTO"] = pd.to_datetime(
    df_tratado["DT_NASCIMENTO"],
    errors="coerce",
    dayfirst=True
)


data_referencia = pd.Timestamp("2026-10-04")


df_tratado["idade"] = (
    (data_referencia - df_tratado["DT_NASCIMENTO"])
    .dt.days
    // 365
)


df_tratado[["nome_candidato","idade"]].head()

                        nome_candidato  idade
0               EDVALDO NOGUEIRA FILHO     65
1  GLAUCIA APARECIDA FERNANDES DE MELO     61
2                ALCIDES RIBEIRO FILHO     72
3       IZADORA CRISTINA DIAS DA SILVA     31
4            ISMAEL FRANKLIN GONCALVES     44

In [11]:
def classificar_cargo(cargo):

    executivo = [
        "PRESIDENTE",
        "GOVERNADOR",
        "VICE-GOVERNADOR",
        "VICE-PRESIDENTE"
    ]

    legislativo = [
        "SENADOR",
        "DEPUTADO FEDERAL",
        "DEPUTADO ESTADUAL",
        "DEPUTADO DISTRITAL"
    ]

    if cargo in executivo:
        return "Executivo"

    elif cargo in legislativo:
        return "Legislativo"

    else:
        return "Outro"


df_tratado["tipo_cargo"] = (
    df_tratado["cargo"]
    .apply(classificar_cargo)
)


df_tratado["tipo_cargo"].value_counts()

tipo_cargo
Legislativo    19643
Outro            653
Executivo        425
Name: count, dtype: int64

In [12]:
df_tratado[
[
"nome_candidato",
"cargo",
"partido",
"estado",
"idade",
"tipo_cargo"
]
].head(10)

,nome_candidato,cargo,partido,estado,idade,tipo_cargo
0,EDVALDO NOGUEIRA FILHO,SENADOR,PDT,SE,65,Legislativo
1,GLAUCIA APARECIDA FERNANDES DE MELO,DEPUTADO FEDERAL,PSDB,GO,61,Legislativo
2,ALCIDES RIBEIRO FILHO,DEPUTADO FEDERAL,PSDB,GO,72,Legislativo
3,IZADORA CRISTINA DIAS DA SILVA,GOVERNADOR,PCO,SP,31,Executivo
4,ISMAEL FRANKLIN GONCALVES,SENADOR,REDE,AM,44,Legislativo
5,MILTON ROGÉRIO MOREIRA PINTO,SENADOR,MOBILIZA,AM,62,Legislativo
6,PAULO RUBEM SANTIAGO FERREIRA,SENADOR,REDE,PE,71,Legislativo
7,ELIETE QUIRINO BARROS PAIXAO,DEPUTADO FEDERAL,PSDB,GO,51,Legislativo
8,RODOLFO VALENTE LIMA,DEPUTADO FEDERAL,PSDB,GO,48,Legislativo
9,JOAO CESAR ANTONIO PEREIRA,DEPUTADO FEDERAL,CIDADANIA,GO,56,Legislativo

In [17]:
PROCESSED_DATA = BASE_DIR / "data" / "processed"

In [18]:
df_tratado.to_parquet(
    PROCESSED_DATA / "candidatos_2026.parquet"
)

In [15]:
print("Linhas:", df_tratado.shape[0])
print("Colunas:", df_tratado.shape[1])

print("\nColunas finais:")
print(df_tratado.columns.tolist())

print("\nTipos de cargo:")
print(df_tratado["tipo_cargo"].value_counts())

Linhas: 20721
Colunas: 49

Colunas finais:
['DT_GERACAO', 'HH_GERACAO', 'ANO_ELEICAO', 'CD_TIPO_ELEICAO', 'NM_TIPO_ELEICAO', 'NR_TURNO', 'CD_ELEICAO', 'DS_ELEICAO', 'DT_ELEICAO', 'TP_ABRANGENCIA', 'estado', 'SG_UE', 'estado_nome', 'CD_CARGO', 'cargo', 'SQ_CANDIDATO', 'NR_CANDIDATO', 'nome_candidato', 'nome_urna', 'NM_SOCIAL_CANDIDATO', 'CD_SITUACAO_CANDIDATURA', 'DS_SITUACAO_CANDIDATURA', 'TP_AGREMIACAO', 'NR_PARTIDO', 'partido', 'nome_partido', 'NR_FEDERACAO', 'NM_FEDERACAO', 'SG_FEDERACAO', 'DS_COMPOSICAO_FEDERACAO', 'SQ_COLIGACAO', 'NM_COLIGACAO', 'DS_COMPOSICAO_COLIGACAO', 'SG_UF_NASCIMENTO', 'DT_NASCIMENTO', 'CD_GENERO', 'genero', 'CD_GRAU_INSTRUCAO', 'escolaridade', 'CD_ESTADO_CIVIL', 'estado_civil', 'CD_COR_RACA', 'cor_raca', 'CD_OCUPACAO', 'ocupacao', 'CD_SIT_TOT_TURNO', 'situacao_final', 'idade', 'tipo_cargo']

Tipos de cargo:
tipo_cargo
Legislativo    19643
Outro            653
Executivo        425
Name: count, dtype: int64