In [2]:
import pandas as pd
from pathlib import Path

In [4]:
arquivo = Path("../data/processed/candidatos_2026.parquet")

df = pd.read_parquet(arquivo)

df.head()

,DT_GERACAO,HH_GERACAO,ANO_ELEICAO,CD_TIPO_ELEICAO,NM_TIPO_ELEICAO,NR_TURNO,CD_ELEICAO,DS_ELEICAO,DT_ELEICAO,TP_ABRANGENCIA,...,CD_ESTADO_CIVIL,estado_civil,CD_COR_RACA,cor_raca,CD_OCUPACAO,ocupacao,CD_SIT_TOT_TURNO,situacao_final,idade,tipo_cargo
0,24/08/2026,16:31:10,2026,2,ELEIÇÃO ORDINÁRIA,1,6259,Eleições Gerais Estaduais 2026,04/10/2026,ESTADUAL,...,3,CASADO(A),3,PARDA,999,OUTROS,-1,Não informado,65,Legislativo
1,24/08/2026,16:31:10,2026,2,ELEIÇÃO ORDINÁRIA,1,6259,Eleições Gerais Estaduais 2026,04/10/2026,ESTADUAL,...,3,CASADO(A),1,BRANCA,602,PECUARISTA,-1,Não informado,61,Legislativo
2,24/08/2026,16:31:10,2026,2,ELEIÇÃO ORDINÁRIA,1,6259,Eleições Gerais Estaduais 2026,04/10/2026,ESTADUAL,...,1,SOLTEIRO(A),1,BRANCA,142,PROFESSOR DE ENSINO SUPERIOR,-1,Não informado,72,Legislativo
3,24/08/2026,16:31:10,2026,2,ELEIÇÃO ORDINÁRIA,1,6259,Eleições Gerais Estaduais 2026,04/10/2026,ESTADUAL,...,1,SOLTEIRO(A),3,PARDA,931,"ESTUDANTE, BOLSISTA, ESTAGIÁRIO E ASSEMELHADOS",-1,Não informado,31,Executivo
4,24/08/2026,16:31:10,2026,2,ELEIÇÃO ORDINÁRIA,1,6259,Eleições Gerais Estaduais 2026,04/10/2026,ESTADUAL,...,3,CASADO(A),5,INDÍGENA,999,OUTROS,-1,Não informado,44,Legislativo

In [5]:
df.shape

(20721, 49)

In [6]:
dim_candidato = df[
    [
        "SQ_CANDIDATO",
        "nome_candidato",
        "nome_urna",
        "idade",
        "genero",
        "cor_raca",
        "ocupacao",
        "escolaridade",
        "estado_civil"
    ]
].copy()

dim_candidato.head()

,SQ_CANDIDATO,nome_candidato,nome_urna,idade,genero,cor_raca,ocupacao,escolaridade,estado_civil
0,260002551550,EDVALDO NOGUEIRA FILHO,EDVALDO,65,MASCULINO,PARDA,OUTROS,SUPERIOR INCOMPLETO,CASADO(A)
1,90002547105,GLAUCIA APARECIDA FERNANDES DE MELO,GLAUCIA MELO,61,FEMININO,BRANCA,PECUARISTA,SUPERIOR COMPLETO,CASADO(A)
2,90002547109,ALCIDES RIBEIRO FILHO,PROFESSOR ALCIDES,72,MASCULINO,BRANCA,PROFESSOR DE ENSINO SUPERIOR,SUPERIOR COMPLETO,SOLTEIRO(A)
3,250002553062,IZADORA CRISTINA DIAS DA SILVA,IZADORA DIAS,31,FEMININO,PARDA,"ESTUDANTE, BOLSISTA, ESTAGIÁRIO E ASSEMELHADOS",SUPERIOR INCOMPLETO,SOLTEIRO(A)
4,40002551283,ISMAEL FRANKLIN GONCALVES,ISMAEL MUNDURUKU,44,MASCULINO,INDÍGENA,OUTROS,SUPERIOR COMPLETO,CASADO(A)

In [7]:
dim_candidato.shape

(20721, 9)

In [8]:
dim_partido = df[
    [
        "NR_PARTIDO",
        "partido",
        "nome_partido",
        "NR_FEDERACAO",
        "NM_FEDERACAO"
    ]
].drop_duplicates()

dim_partido.head()

,NR_PARTIDO,partido,nome_partido,NR_FEDERACAO,NM_FEDERACAO
0,12,PDT,PARTIDO DEMOCRÁTICO TRABALHISTA,-1,Não informado
1,45,PSDB,PARTIDO DA SOCIAL DEMOCRACIA BRASILEIRA,100,FEDERAÇÃO PSDB CIDADANIA
3,29,PCO,PARTIDO DA CAUSA OPERÁRIA,-1,Não informado
4,18,REDE,REDE SUSTENTABILIDADE,102,FEDERAÇÃO PSOL REDE
5,33,MOBILIZA,MOBILIZAÇÃO NACIONAL,-1,Não informado

In [9]:
dim_partido.shape

(30, 5)

In [10]:
dim_cargo = df[
    [
        "CD_CARGO",
        "cargo",
        "tipo_cargo"
    ]
].drop_duplicates()

dim_cargo.head()

     CD_CARGO               cargo   tipo_cargo
0           5             SENADOR  Legislativo
1           6    DEPUTADO FEDERAL  Legislativo
3           3          GOVERNADOR    Executivo
11          7   DEPUTADO ESTADUAL  Legislativo
466         8  DEPUTADO DISTRITAL  Legislativo

In [11]:
dim_cargo.shape

(10, 3)

In [12]:
dim_estado = df[
    [
        "estado",
        "estado_nome"
    ]
].drop_duplicates()

dim_estado.head()

  estado estado_nome
0     SE     SERGIPE
1     GO       GOIÁS
3     SP   SÃO PAULO
4     AM    AMAZONAS
6     PE  PERNAMBUCO

In [13]:
dim_estado.shape

(28, 2)

In [14]:
dim_estado.sort_values("estado")

     estado          estado_nome
723      AC                 ACRE
2166     AL              ALAGOAS
4        AM             AMAZONAS
1464     AP                AMAPÁ
794      BA                BAHIA
2163     BR               BRASIL
1616     CE                CEARÁ
14       DF     DISTRITO FEDERAL
1300     ES       ESPÍRITO SANTO
1        GO                GOIÁS
153      MA             MARANHÃO
106      MG         MINAS GERAIS
644      MS   MATO GROSSO DO SUL
1719     MT          MATO GROSSO
777      PA                 PARÁ
943      PB              PARAÍBA
6        PE           PERNAMBUCO
1301     PI                PIAUÍ
1549     PR               PARANÁ
20       RJ       RIO DE JANEIRO
1785     RN  RIO GRANDE DO NORTE
325      RO             RONDÔNIA
1800     RR              RORAIMA
1040     RS    RIO GRANDE DO SUL
24       SC       SANTA CATARINA
0        SE              SERGIPE
3        SP            SÃO PAULO
1820     TO            TOCANTINS

In [16]:
dim_estado = dim_estado[
    dim_estado["estado"] != "BR"
]

dim_estado.shape

(27, 2)

In [17]:
dim_estado = (
    dim_estado
    .sort_values("estado")
    .reset_index(drop=True)
)

dim_estado["id_estado"] = dim_estado.index + 1

dim_estado = dim_estado[
    [
        "id_estado",
        "estado",
        "estado_nome"
    ]
]

dim_estado.head()

   id_estado estado estado_nome
0          1     AC        ACRE
1          2     AL     ALAGOAS
2          3     AM    AMAZONAS
3          4     AP       AMAPÁ
4          5     BA       BAHIA

In [18]:
fato_candidatura = df[
    [
        "SQ_CANDIDATO",
        "NR_PARTIDO",
        "CD_CARGO",
        "estado",
        "ANO_ELEICAO",
        "situacao_final"
    ]
].copy()

fato_candidatura.head()

   SQ_CANDIDATO  NR_PARTIDO  CD_CARGO estado  ANO_ELEICAO situacao_final
0  260002551550          12         5     SE         2026  Não informado
1   90002547105          45         6     GO         2026  Não informado
2   90002547109          45         6     GO         2026  Não informado
3  250002553062          29         3     SP         2026  Não informado
4   40002551283          18         5     AM         2026  Não informado

In [19]:
fato_candidatura.shape

(20721, 6)

In [20]:
fato_candidatura = fato_candidatura.merge(
    dim_estado,
    on="estado",
    how="left"
)

fato_candidatura.head()

,SQ_CANDIDATO,NR_PARTIDO,CD_CARGO,estado,ANO_ELEICAO,situacao_final,id_estado,estado_nome
0,260002551550,12,5,SE,2026,Não informado,25.0,SERGIPE
1,90002547105,45,6,GO,2026,Não informado,9.0,GOIÁS
2,90002547109,45,6,GO,2026,Não informado,9.0,GOIÁS
3,250002553062,29,3,SP,2026,Não informado,26.0,SÃO PAULO
4,40002551283,18,5,AM,2026,Não informado,3.0,AMAZONAS

In [21]:
fato_candidatura["id_estado"].isna().sum()

np.int64(26)

In [22]:
fato_candidatura[
    fato_candidatura["id_estado"].isna()
][
    [
        "estado",
        "SQ_CANDIDATO",
        "CD_CARGO"
    ]
]

      estado  SQ_CANDIDATO  CD_CARGO
2163      BR  280002539826         1
2304      BR  280002539825         2
4736      BR  280002538811         1
4738      BR  280002551932         1
4739      BR  280002551547         1
7314      BR  280002551975         1
7456      BR  280002548140         2
7457      BR  280002553883         2
7458      BR  280002551933         2
7459      BR  280002552485         2
9889      BR  280002541457         1
9890      BR  280002540694         1
10047     BR  280002552486         2
12519     BR  280002553884         1
12686     BR  280002542549         2
12687     BR  280002541458         2
12688     BR  280002540693         2
15281     BR  280002538812         2
17659     BR  280002551544         1
17660     BR  280002552484         1
17801     BR  280002551546         2
20234     BR  280002542548         1
20235     BR  280002548139         1
20239     BR  280002552487         1
20381     BR  280002551543         2
20382     BR  280002551976         2

In [23]:
fato_candidatura = fato_candidatura[
    fato_candidatura["id_estado"].notna()
]

In [24]:
fato_candidatura = fato_candidatura.drop(
    columns=[
        "estado",
        "estado_nome"
    ]
)

fato_candidatura.head()

   SQ_CANDIDATO  NR_PARTIDO  CD_CARGO  ANO_ELEICAO situacao_final  id_estado
0  260002551550          12         5         2026  Não informado       25.0
1   90002547105          45         6         2026  Não informado        9.0
2   90002547109          45         6         2026  Não informado        9.0
3  250002553062          29         3         2026  Não informado       26.0
4   40002551283          18         5         2026  Não informado        3.0

In [36]:
dim_partido = (
    dim_partido
    .sort_values("NR_PARTIDO")
    .reset_index(drop=True)
)

dim_partido["id_partido"] = dim_partido.index + 1


dim_partido = dim_partido[
    [
        "id_partido",
        "NR_PARTIDO",
        "partido",
        "nome_partido",
        "NR_FEDERACAO",
        "NM_FEDERACAO"
    ]
]

dim_partido.head()

,id_partido,NR_PARTIDO,partido,nome_partido,NR_FEDERACAO,NM_FEDERACAO
0,1,10,REPUBLICANOS,REPUBLICANOS,-1,Não informado
1,2,11,PP,PROGRESSISTAS,104,FEDERAÇÃO UNIÃO PROGRESSISTA
2,3,12,PDT,PARTIDO DEMOCRÁTICO TRABALHISTA,-1,Não informado
3,4,13,PT,PARTIDO DOS TRABALHADORES,101,FEDERAÇÃO BRASIL DA ESPERANÇA - FE BRASIL
4,5,14,MISSÃO,PARTIDO MISSÃO,-1,Não informado

In [37]:
dim_partido.shape

(30, 6)

In [38]:
fato_candidatura["id_partido"].isna().sum()

np.int64(0)

In [40]:
fato_candidatura.columns.tolist()

['SQ_CANDIDATO',
 'NR_PARTIDO',
 'CD_CARGO',
 'ANO_ELEICAO',
 'situacao_final',
 'id_estado',
 'id_partido_x',
 'id_partido_y',
 'id_partido']

In [41]:
fato_candidatura["id_partido"].isna().sum()

np.int64(0)

In [42]:
fato_candidatura.head()

,SQ_CANDIDATO,NR_PARTIDO,CD_CARGO,ANO_ELEICAO,situacao_final,id_estado,id_partido_x,id_partido_y,id_partido
0,260002551550,12,5,2026,Não informado,25.0,3,3,3
1,90002547105,45,6,2026,Não informado,9.0,24,24,24
2,90002547109,45,6,2026,Não informado,9.0,24,24,24
3,250002553062,29,3,2026,Não informado,26.0,16,16,16
4,40002551283,18,5,2026,Não informado,3.0,8,8,8

In [43]:
fato_candidatura = fato_candidatura.drop(
    columns=["id_partido_x"]
)

fato_candidatura = fato_candidatura.rename(
    columns={
        "id_partido_y": "id_partido"
    }
)

In [46]:
fato_candidatura.columns.tolist()

['SQ_CANDIDATO',
 'NR_PARTIDO',
 'CD_CARGO',
 'ANO_ELEICAO',
 'situacao_final',
 'id_estado',
 'id_partido',
 'id_partido']

In [47]:
dim_cargo = (
    dim_cargo
    .sort_values("CD_CARGO")
    .reset_index(drop=True)
)

dim_cargo["id_cargo"] = dim_cargo.index + 1


dim_cargo = dim_cargo[
    [
        "id_cargo",
        "CD_CARGO",
        "cargo",
        "tipo_cargo"
    ]
]


dim_cargo.head()

   id_cargo  CD_CARGO            cargo   tipo_cargo
0         1         1       PRESIDENTE    Executivo
1         2         2  VICE-PRESIDENTE    Executivo
2         3         3       GOVERNADOR    Executivo
3         4         4  VICE-GOVERNADOR    Executivo
4         5         5          SENADOR  Legislativo

In [48]:
dim_cargo.shape

(10, 4)

In [50]:
fato_candidatura = fato_candidatura.merge(
    dim_cargo[
        [
            "CD_CARGO",
            "id_cargo"
        ]
    ],
    on="CD_CARGO",
    how="left"
)

In [51]:
fato_candidatura = fato_candidatura.loc[:, ~fato_candidatura.columns.duplicated()]

In [52]:
fato_candidatura.columns.tolist()

['SQ_CANDIDATO',
 'NR_PARTIDO',
 'CD_CARGO',
 'ANO_ELEICAO',
 'situacao_final',
 'id_estado',
 'id_partido',
 'id_cargo_x',
 'id_cargo_y']

In [53]:
fato_candidatura = fato_candidatura.merge(
    dim_cargo[
        [
            "CD_CARGO",
            "id_cargo"
        ]
    ],
    on="CD_CARGO",
    how="left"
)

In [54]:
fato_candidatura.head()

,SQ_CANDIDATO,NR_PARTIDO,CD_CARGO,ANO_ELEICAO,situacao_final,id_estado,id_partido,id_cargo_x,id_cargo_y,id_cargo
0,260002551550,12,5,2026,Não informado,25.0,3,5,5,5
1,90002547105,45,6,2026,Não informado,9.0,24,6,6,6
2,90002547109,45,6,2026,Não informado,9.0,24,6,6,6
3,250002553062,29,3,2026,Não informado,26.0,16,3,3,3
4,40002551283,18,5,2026,Não informado,3.0,8,5,5,5

In [55]:
fato_candidatura["id_cargo"].isna().sum()

np.int64(0)

In [61]:
fato_candidatura = fato_candidatura.drop(
    columns=[
        "id_cargo_x",
        "id_cargo_y"
    ]
)

In [62]:
fato_candidatura.columns.tolist()

['SQ_CANDIDATO',
 'NR_PARTIDO',
 'CD_CARGO',
 'ANO_ELEICAO',
 'situacao_final',
 'id_estado',
 'id_partido']

In [63]:
fato_candidatura = fato_candidatura.merge(
    dim_cargo[
        [
            "CD_CARGO",
            "id_cargo"
        ]
    ],
    on="CD_CARGO",
    how="left"
)

In [64]:
fato_candidatura.columns.tolist()

['SQ_CANDIDATO',
 'NR_PARTIDO',
 'CD_CARGO',
 'ANO_ELEICAO',
 'situacao_final',
 'id_estado',
 'id_partido',
 'id_cargo']

In [65]:
fato_candidatura["id_cargo"].isna().sum()

np.int64(0)

In [66]:
fato_candidatura = fato_candidatura[
    [
        "SQ_CANDIDATO",
        "id_partido",
        "id_cargo",
        "id_estado",
        "ANO_ELEICAO",
        "situacao_final"
    ]
]

In [67]:
fato_candidatura.head()

   SQ_CANDIDATO  id_partido  id_cargo  id_estado  ANO_ELEICAO situacao_final
0  260002551550           3         5       25.0         2026  Não informado
1   90002547105          24         6        9.0         2026  Não informado
2   90002547109          24         6        9.0         2026  Não informado
3  250002553062          16         3       26.0         2026  Não informado
4   40002551283           8         5        3.0         2026  Não informado

In [68]:
fato_candidatura.shape

(20695, 6)

In [69]:
print("Partido:", fato_candidatura["id_partido"].isna().sum())
print("Cargo:", fato_candidatura["id_cargo"].isna().sum())
print("Estado:", fato_candidatura["id_estado"].isna().sum())

Partido: 0
Cargo: 0
Estado: 0

In [70]:
dim_candidato = df[
    [
        "SQ_CANDIDATO",
        "nome_candidato",
        "nome_urna",
        "idade",
        "genero",
        "cor_raca",
        "ocupacao",
        "escolaridade",
        "estado_civil"
    ]
].drop_duplicates()

In [71]:
dim_candidato.shape

(20721, 9)

In [72]:
dim_candidato = (
    dim_candidato
    .sort_values("SQ_CANDIDATO")
    .reset_index(drop=True)
)

dim_candidato["id_candidato"] = dim_candidato.index + 1

In [73]:
dim_candidato = dim_candidato[
    [
        "id_candidato",
        "SQ_CANDIDATO",
        "nome_candidato",
        "nome_urna",
        "idade",
        "genero",
        "cor_raca",
        "ocupacao",
        "escolaridade",
        "estado_civil"
    ]
]

In [74]:
dim_candidato.head()

,id_candidato,SQ_CANDIDATO,nome_candidato,nome_urna,idade,genero,cor_raca,ocupacao,escolaridade,estado_civil
0,1,10002532416,ADGICLEIA DOS SANTOS GUIMARÃES,DR.. KEL GUIMARÃES,35,FEMININO,PARDA,MÉDICO,SUPERIOR COMPLETO,CASADO(A)
1,2,10002532417,FÁBIO DE ARAÚJO FREITAS,FÁBIO ARAÚJO,45,MASCULINO,PARDA,VEREADOR,SUPERIOR COMPLETO,CASADO(A)
2,3,10002532418,JOZINEY ALVES AMORIM,NEY AMORIM,49,MASCULINO,BRANCA,EMPRESÁRIO,SUPERIOR COMPLETO,CASADO(A)
3,4,10002532419,ANTÔNIA LUCILEIA CRUZ RAMOS CÂMARA,ANTÔNIA LÚCIA,56,FEMININO,PARDA,DEPUTADO,SUPERIOR COMPLETO,DIVORCIADO(A)
4,5,10002532420,MINORU MARTINS KINPARA,MINORU KINPARA,57,MASCULINO,PARDA,PROFESSOR DE ENSINO SUPERIOR,SUPERIOR COMPLETO,CASADO(A)

In [75]:
dim_candidato["id_candidato"].nunique()

20721

In [76]:
dim_candidato.shape[0]

20721

In [77]:
from pathlib import Path

PROCESSED_DATA = Path("../data/processed")

PROCESSED_DATA.mkdir(
    parents=True,
    exist_ok=True
)

In [78]:
dim_candidato.to_parquet(
    PROCESSED_DATA / "dim_candidato.parquet"
)

dim_partido.to_parquet(
    PROCESSED_DATA / "dim_partido.parquet"
)

dim_cargo.to_parquet(
    PROCESSED_DATA / "dim_cargo.parquet"
)

dim_estado.to_parquet(
    PROCESSED_DATA / "dim_estado.parquet"
)

fato_candidatura.to_parquet(
    PROCESSED_DATA / "fato_candidatura.parquet"
)

In [79]:
list(PROCESSED_DATA.glob("*.parquet"))

[WindowsPath('../data/processed/candidatos_2026.parquet'),
 WindowsPath('../data/processed/dim_candidato.parquet'),
 WindowsPath('../data/processed/dim_cargo.parquet'),
 WindowsPath('../data/processed/dim_estado.parquet'),
 WindowsPath('../data/processed/dim_partido.parquet'),
 WindowsPath('../data/processed/fato_candidatura.parquet')]